- name: set hostname
  ansible.builtin.shell: set-hostname elasticsearch

- name: Copy Elastic Repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: Start Elasticsearch
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Install Kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed

- name: Start Kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: started
    enabled: yes

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy Nginx Config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: started




